include:
- ./toot/__init__.py
- ./toot/toot.py
- ./toot/requirements.txt
- ./toot/build.sh
kind: ArchiveUploadSpec
name: toot---init---py-IPCp

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: toot
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python-api
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://toot---init---py-IPCp
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-17T01:24:12Z"
