apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: toot
spec:
  createingress: false
  functionref:
    functionweights: null
    name: toot
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /toot/{index}/{date:[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /toot/{index}/{date:[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]}
