apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: sudo
spec:
  createingress: false
  functionref:
    functionweights: null
    name: sudo
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /sudo/{index}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /sudo/{index}
