include:
- ./ingester/__init__.py
- ./ingester/ingester.py
- ./ingester/requirements.txt
- ./ingester/build.sh
kind: ArchiveUploadSpec
name: ingester---init---py-56Dp

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: ingester
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python-ingest
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://ingester---init---py-56Dp
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-17T09:23:03Z"
